name: islami
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.3
  shared_preferences: ^2.5.4
  introduction_screen: ^4.0.0
  carousel_slider: ^5.1.1
  http: ^1.6.0
  audioplayers: ^6.3.0
  provider: ^6.1.5+1
  intl: ^0.20.2
  auto_size_text: ^3.0.0
  dropdown_search: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: "^0.14.4"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launcher_icon.png"
  min_sdk_android: 21 

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/texts/
  
  fonts:
    - family: QPC_Hafs
      fonts:
        - asset: assets/fonts/QPC_Hafs.ttf  
